#!/bin/bash
# =============================================================================
# Way Back Home: Environment Variables
# =============================================================================
# Generated by setup_env.sh on Fri Mar 13 04:16:56 PM UTC 2026
# Source this file before running agents or deploying services.
# =============================================================================

# Google Cloud Configuration
export GOOGLE_CLOUD_PROJECT="waybackhome-opu0b43h0ony38att4"
export PROJECT_ID="waybackhome-opu0b43h0ony38att4"
export REGION="us-central1"
export GOOGLE_CLOUD_LOCATION="us-central1"

# ADK Configuration - Required for adk web and agent execution
export GOOGLE_GENAI_USE_VERTEXAI=true

# Participant Configuration (from config.json)
# This is used by the agent's before_agent_callback to fetch participant data
export PARTICIPANT_ID="e38ffefb"

# Backend API URL (for agent tools to confirm location, fetch participant data)
export BACKEND_URL="https://api.waybackhome.dev"

# Service Account for Cloud Run deployments
export SERVICE_ACCOUNT="way-back-home-sa@waybackhome-opu0b43h0ony38att4.iam.gserviceaccount.com"
export REPO_NAME="way-back-home"

# Google Cloud MCP server for BigQuery URL
export BIGQUERY_MCP_URL="https://bigquery.googleapis.com/mcp"

# These will be set after deploying services:
# export MCP_SERVER_URL="https://location-analyzer-xxx.a.run.app"
# export LEVEL1_AGENT_URL="https://mission-analysis-ai-xxx.a.run.app"

echo "Environment loaded for project: $PROJECT_ID (Vertex AI mode)"
if [ -n "$PARTICIPANT_ID" ]; then
    echo "Participant ID: $PARTICIPANT_ID"
fi
export MCP_SERVER_URL="https://location-analyzer-hs3litbjfa-uc.a.run.app"
export LEVEL1_AGENT_URL="https://mission-analysis-ai-hs3litbjfa-uc.a.run.app"
